/** @module containers/Game/services/constants/duelParameters */

/**
  @brief The object of duel economics
  @description It contains
  chanceOfMovementRandomBooster,
  warmupDuration (in seconds),
  duelDuration (in seconds),
  numberOfAttackIntervals,
  intervalDurationRandomBooster,
  chanceOfOffensiveMovement (chanceOfOffensiveMovement + chanceOfDefensiveMovement = 1.0),
  chanceOfDefensiveMovement (chanceOfOffensiveMovement + chanceOfDefensiveMovement = 1.0),
  chanceOfProbeMovement (chanceOfProbeMovement + chanceOfSwitchLeadingSideMovement = 1.0),
  chanceOfSwitchLeadingSideMovement (chanceOfProbeMovement + chanceOfSwitchLeadingSideMovement = 1.0),
  attackIntervalDurationCoefficient,
  probeIntervalDurationCoefficient,
  movementDuration (in seconds),
  attackRestDurationCoefficient,
  probeRestDurationCoefficient,
  reactionTimeCoefficient,
  chanceOfMiss,
  missAngle (in radians),
  bruteForceAttackHealthLoss,
  deceptiveAttackHealthLoss,
  bruteForceAttackDefenseBlockSuccessHealthLoss,
  bruteForceAttackDefenseDodgeSuccessHealthLoss,
  bruteForceAttackDefenseFailHealthLoss,
  deceptiveAttackDefenseBlockSuccessHealthLoss,
  deceptiveAttackDefenseDodgeSuccessHealthLoss,
  deceptiveAttackDefenseFailHealthLoss,
  slowMotionCooldownDuration (in seconds),
  slowMotionMovementsNumber,
  slowMotionSpeedMultiplier.
*/
const duelParameters = {
  chanceOfMovementRandomBooster: 0.1,
  warmupDuration: 3.0,
  duelDuration: 60.0,
  numberOfAttackIntervals: 12,
  intervalDurationRandomBooster: 0.1,
  chanceOfOffensiveMovement: 0.5,
  chanceOfDefensiveMovement: 0.5,
  chanceOfProbeMovement: 1.0,
  chanceOfSwitchLeadingSideMovement: 0.0,
  attackIntervalDurationCoefficient: 4.0,
  probeIntervalDurationCoefficient: 3.0,
  movementDuration: 0.6,
  attackRestDurationCoefficient: 1.0,
  probeRestDurationCoefficient: 3.0,
  reactionTimeCoefficient: 0.35,
  chanceOfMiss: 0.5,
  missAngle: Math.PI / 6.0,
  bruteForceAttackHealthLoss: 0.5,
  deceptiveAttackHealthLoss: 0.0,
  bruteForceAttackDefenseBlockSuccessHealthLoss: 1.5,
  bruteForceAttackDefenseDodgeSuccessHealthLoss: 0.0,
  bruteForceAttackDefenseFailHealthLoss: 5.0,
  deceptiveAttackDefenseBlockSuccessHealthLoss: 0.5,
  deceptiveAttackDefenseDodgeSuccessHealthLoss: 0.0,
  deceptiveAttackDefenseFailHealthLoss: 10.0,
  slowMotionCooldownDuration: 3.0,
  slowMotionMovementsNumber: 5,
  slowMotionSpeedMultiplier: 0.3,
};

export default duelParameters;
