const duelAnimationsNames = {
  offensive: {
    bruteForceAttack: [
      'cross-up-left',
      'cross-up-right',
      'cross-down-left',
      'cross-down-right',
      'hook-left',
      'hook-right',
      'uppercut-up-left',
      'uppercut-up-right',
      'uppercut-down-left',
      'uppercut-down-right',
      'overhand-left',
      'overhand-right',
    ],
    deceptiveAttack: [
      'jab',
      'cross-up-left',
      'cross-up-right',
      'cross-down-left',
      'cross-down-right',
      'hook-left',
      'hook-right',
      'uppercut-up-left',
      'uppercut-up-right',
      'uppercut-down-left',
      'uppercut-down-right',
    ],
    effectiveAttack: [
      'jab',
      'cross-up-left',
      'cross-up-right',
      'cross-down-left',
      'cross-down-right',
      'hook-left',
      'hook-right',
      'uppercut-up-left',
      'uppercut-up-right',
      'uppercut-down-left',
      'uppercut-down-right',
    ],
  },
  defensive: {
    block: [
      'block-up-left',
      'block-up-right',
      'block-down-left',
      'block-down-right',
      'block-front',
    ],
    dodge: [
      'slip-left',
      'slip-right',
      'roll-left',
      'roll-right',
      'dive-left',
      'dive-right',
    ],
    counterAttack: [
      'cross-up-left',
      'cross-up-right',
      'overhand-left',
      'overhand-right',
    ],
  },
  probe: [
    'change-stand',
    'step-forward',
    'step-backward',
    'step-to-the-left',
    'step-to-the-right',
    'slip-left',
    'slip-right',
    'roll-left',
    'roll-right',
    'dive-left',
    'dive-right',
    'jab',
  ],
};

export default duelAnimationsNames;
