const duelAnimationNames = {
  lower: [
    'step-forward',
    'step-backward',
    'step-to-the-left',
    'step-to-the-right',
  ],
  upper: {
    offensive: {
      bruteForceAttack: [
        'cross-up-left',
        'cross-up-right',
        'cross-down-left',
        'cross-down-right',
        'hook-up-left',
        'hook-up-right',
        'hook-down-left',
        'hook-down-right',
        'uppercut-up-left',
        'uppercut-up-right',
        'uppercut-down-left',
        'uppercut-down-right',
        'overhand-left',
        'overhand-right',
      ],
      deceptiveAttack: [
        'jab',
        'cross-up-left',
        'cross-up-right',
        'cross-down-left',
        'cross-down-right',
        'hook-up-left',
        'hook-up-right',
        'hook-down-left',
        'hook-down-right',
        'uppercut-up-left',
        'uppercut-up-right',
        'uppercut-down-left',
        'uppercut-down-right',
      ],
      counterAttack: [
        'cross-up-left',
        'cross-up-right',
        'overhand-left',
        'overhand-right',
      ],
    },
    defensive: {
      block: [
        'block-up-left',
        'block-up-right',
        'block-down-left',
        'block-down-right',
        'block-front',
      ],
      dodge: [
        'slip-left',
        'slip-right',
        'roll-left',
        'roll-right',
        'dive-left',
        'dive-right',
      ],
    },
    probe: [
      'change-stand',
      'slip-left',
      'slip-right',
      'roll-left',
      'roll-right',
      'dive-left',
      'dive-right',
      'jab',
    ],
  },
  whole: [
    'defeat-1',
    'defeat-2',
    'falling-backward',
    'falling-forward',
    'getting-up-backward',
    'getting-up-forward',
    'standing-1',
    'standing-2',
    'victory-1',
    'victory-2',
    'warming-up-1',
    'warming-up-2',
  ],
};

export default duelAnimationNames;
